import type { Metadata } from "next";
import { Inter as FontSans, Fraunces as FontSerif } from "next/font/google";
import "@/styles/reset.css";
import "@/styles/globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer"

import { cn } from "@/lib/utils";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const fontSerif = FontSerif({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          fontSerif.variable
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
